1.8.x
anteatersa/Wagtail-Image-Folders pull request #1
Opened 2017-03-21 03:59 UTC by roshangeorge93

Hi @anteatersa,

I've added support for Wagtail 1.8.x.

I've also added the support for physical folders.

Cheers!

2017-03-22 10:59 UTC, anteatersa requested changes
Hi Roshan, thanks for all your work on this, it looks very good. 

I do have a problem with the creation of folders matching the database folders e.g. in models.py when you create the folders:

 os.makedirs(self.get_complete_path())

You can actually enter a malicious name such as ../../../../hackme which will create a folder above the media/original_images folder which they are then able to upload files to. This may be ok for users you trust but could be used to exploit the server.

It may be possible to perform validation of folder names but allowing users to choose the name of a folder in the filesystem is inherently dangerous. So I propose to lose this feature altogether and just have all files in one directory or have subfolders which are just md5 hashes of folder name.

Let me know your thoughts.

2017-03-23 14:18 UTC, roshangeorge93 commented
Hi @anteatersa,

Thanks for the feedback. 

Good catch,  I had missed out validations on folder names. I'm gonna add validations for the names right away.

I had added support for physical folders as I required it for my work. I can remove it if you want me to. But do you think there are any other potential risks?

Thanks.

2017-03-23 15:26 UTC, anteatersa commented
Hi Roshan,

I will merge your changes, but maybe comment out the folder paths. Thanks
again for the changes, I haven't gotten around to updating my Wagtail sites
to 1.8 yet!

Regards,
Adam

On 23 March 2017 at 14:18, Roshan George <notifications@github.com> wrote:

> Hi @anteatersa <https://github.com/anteatersa>,
>
> Thanks for the feedback.
>
> Good catch, I had missed out validations on folder names. I'm gonna add
> validations for the names right away.
>
> I had added support for physical folders as I required it for my work. I
> can remove it if you want me to. But do you think there are any other
> potential risks?
>
> Thanks.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/anteatersa/Wagtail-Image-Folders/pull/1#issuecomment-288733203>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AI6GScVFNyBqkGpax_Ipdzr1TqpaFOL1ks5ron8xgaJpZM4MjTqN>
> .
>

2017-03-28 09:38 UTC, merged

2017-03-30 11:57 UTC, roshangeorge93 commented
Hey Adam,

I'm working on removing the physical folder feature.

However, I've also added few validators to handle the cases that you mentioned.

So do you want the physical folder feature removed or do you want to keep it along with the validators?

2017-03-30 12:58 UTC, anteatersa commented
You could leave it in but have a setting in the django settings file to disable/enable?

2017-03-30 15:28 UTC, roshangeorge93 commented
Sure. I'll add that feature and send another PR.